{{- if .Values.database.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: chatapp-mysql-vpa
  labels:
    app: chatapp
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: chatapp-database
  updatePolicy:
    updateMode: "Auto"
{{- end }}
